#pragma once

/***************************************************/
/***            Sensors/Devices Amount           ***/
/***************************************************/
#define ENGINE_VALVE_AMOUNT             2
#define ENGINE_TELECOMMUNICATION_AMOUNT 1
#define ENGINE_THERMISTANCE_AMOUNT      8
#define ENGINE_PRESSURE_SENSOR_AMOUNT   4
#define ENGINE_IGNITER_AMOUNT           2

/***************************************************/
/***           Peripheral Distribution           ***/
/***************************************************/
#define ENGINE_GPIO_PER_VALVE 2
#define ENGINE_GPIO_PER_IGNITER 1

/***************************************************/
/***              Peripheral Amount              ***/
/***************************************************/
#define ENGINE_PWM_AMOUNT         2
#define ENGINE_ADC_AMOUNT         1
#define ENGINE_ADC_CHANNEL_AMOUNT 16
#define ENGINE_UART_AMOUNT        1
#define ENGINE_GPIO_AMOUNT        (ENGINE_GPIO_PER_VALVE * ENGINE_VALVE_AMOUNT) + (ENGINE_IGNITER_AMOUNT * ENGINE_GPIO_PER_IGNITER)

/***************************************************/
/***                Array Indexes                ***/
/***************************************************/
#define ENGINE_IPA_VALVE_INDEX     0
#define ENGINE_NOS_VALVE_INDEX     1

#define ENGINE_IPA_VALVE_PWM_INDEX 0
#define ENGINE_NOS_VALVE_PWM_INDEX 1

#define ENGINE_NOS_TANK_PRESSURE_SENSOR_INDEX           0
//#define ENGINE_NOS_MANIFOLD_PRESSURE_SENSOR_INDEX       1
//#define ENGINE_IPA_MANIFOLD_PRESSURE_SENSOR_INDEX       2
#define ENGINE_COMBUSTION_CHAMBER_PRESSURE_SENSOR_INDEX 1

#define ENGINE_COMBUSTION_CHAMBER_1_THERMISTANCE_INDEX 0
#define ENGINE_COMBUSTION_CHAMBER_2_THERMISTANCE_INDEX 1
#define ENGINE_COMBUSTION_CHAMBER_3_THERMISTANCE_INDEX 2
#define ENGINE_COMBUSTION_CHAMBER_4_THERMISTANCE_INDEX 3
#define ENGINE_COMBUSTION_CHAMBER_5_THERMISTANCE_INDEX 4
#define ENGINE_COMBUSTION_CHAMBER_6_THERMISTANCE_INDEX 5
#define ENGINE_COMBUSTION_CHAMBER_7_THERMISTANCE_INDEX 6
#define ENGINE_COMBUSTION_CHAMBER_8_THERMISTANCE_INDEX 7

#define ENGINE_TELECOMMUNICATION_UART_INDEX 0

#define ENGINE_IGNITER_1_GPIO_INDEX 0
#define ENGINE_IGNITER_2_GPIO_INDEX 1
#define ENGINE_NOS_VALVE_CLOSED_GPIO_INDEX 2
#define ENGINE_NOS_VALVE_CLOSED_GPIO_INDEX 3
#define ENGINE_IPA_VALVE_CLOSED_GPIO_INDEX 4
#define ENGINE_IPA_VALVE_CLOSED_GPIO_INDEX 5

#define ENGINE_COMBUSTION_CHAMBER_1_THERMISTANCE_ADC_CHANNEL_INDEX    0
#define ENGINE_COMBUSTION_CHAMBER_2_THERMISTANCE_ADC_CHANNEL_INDEX    1
#define ENGINE_COMBUSTION_CHAMBER_3_THERMISTANCE_ADC_CHANNEL_INDEX    2
#define ENGINE_COMBUSTION_CHAMBER_4_THERMISTANCE_ADC_CHANNEL_INDEX    3
#define ENGINE_COMBUSTION_CHAMBER_5_THERMISTANCE_ADC_CHANNEL_INDEX    4
#define ENGINE_COMBUSTION_CHAMBER_6_THERMISTANCE_ADC_CHANNEL_INDEX    5
#define ENGINE_COMBUSTION_CHAMBER_7_THERMISTANCE_ADC_CHANNEL_INDEX    6
#define ENGINE_COMBUSTION_CHAMBER_8_THERMISTANCE_ADC_CHANNEL_INDEX    7
#define ENGINE_NOS_TANK_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1           8
#define ENGINE_NOS_TANK_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2           9
#define ENGINE_NOS_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1       10
#define ENGINE_NOS_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2       11
#define ENGINE_IPA_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1       12
#define ENGINE_IPA_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2       13
#define ENGINE_COMBUSTION_CHAMBER_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1 14
#define ENGINE_COMBUSTION_CHAMBER_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2 15

