#pragma once

#define ENGINE_PWM_AMOUNT         2
#define ENGINE_ADC_AMOUNT         1
#define ENGINE_ADC_CHANNEL_AMOUNT 16
#define ENGINE_UART_AMOUNT        1
#define ENGINE_GPIO_AMOUNT        1

#define ENGINE_VALVE_AMOUNT             2
#define ENGINE_TELECOMMUNICATION_AMOUNT 1
#define ENGINE_THERMISTANCE_AMOUNT      8
#define ENGINE_PRESSURE_SENSOR_AMOUNT   3
#define ENGINE_EMATCH_AMOUNT            1

#define ENGINE_IPA_VALVE_INDEX     0
#define ENGINE_IPA_VALVE_PWM_INDEX 0
#define ENGINE_NOS_VALVE_INDEX     1
#define ENGINE_NOS_VALVE_PWM_INDEX 1