#pragma once

#define ENGINE_PWM_AMOUNT         2
#define ENGINE_ADC_AMOUNT         1
#define ENGINE_ADC_CHANNEL_AMOUNT 16
#define ENGINE_UART_AMOUNT        1
#define ENGINE_GPIO_AMOUNT        1

#define ENGINE_VALVE_AMOUNT             2
#define ENGINE_TELECOMMUNICATION_AMOUNT 1
#define ENGINE_THERMISTANCE_AMOUNT      8
#define ENGINE_PRESSURE_SENSOR_AMOUNT   4
#define ENGINE_EMATCH_AMOUNT            1

#define ENGINE_IPA_VALVE_INDEX     0
#define ENGINE_NOS_VALVE_INDEX     1

// CHECK IF GOOD
#define ENGINE_IPA_VALVE_PWM_INDEX 0
#define ENGINE_NOS_VALVE_PWM_INDEX 1

#define ENGINE_NOS_TANK_PRESSURE_SENSOR_INDEX           0
#define ENGINE_NOS_MANIFOLD_PRESSURE_SENSOR_INDEX       1
#define ENGINE_IPA_MANIFOLD_PRESSURE_SENSOR_INDEX       2
#define ENGINE_COMBUSTION_CHAMBER_PRESSURE_SENSOR_INDEX 3

#define ENGINE_COMBUSTION_CHAMBER_1_THERMISTANCE_INDEX 0
#define ENGINE_COMBUSTION_CHAMBER_2_THERMISTANCE_INDEX 1
#define ENGINE_COMBUSTION_CHAMBER_3_THERMISTANCE_INDEX 2
#define ENGINE_COMBUSTION_CHAMBER_4_THERMISTANCE_INDEX 3
#define ENGINE_COMBUSTION_CHAMBER_5_THERMISTANCE_INDEX 4
#define ENGINE_COMBUSTION_CHAMBER_6_THERMISTANCE_INDEX 5
#define ENGINE_COMBUSTION_CHAMBER_7_THERMISTANCE_INDEX 6
#define ENGINE_COMBUSTION_CHAMBER_8_THERMISTANCE_INDEX 7

// CHECK IF GOOD
#define ENGINE_NOS_TANK_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1           0
#define ENGINE_NOS_TANK_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2           1
#define ENGINE_NOS_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1       2
#define ENGINE_NOS_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2       3
#define ENGINE_IPA_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1       4
#define ENGINE_IPA_MANIFOLD_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2       5
#define ENGINE_COMBUSTION_CHAMBER_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_1 6
#define ENGINE_COMBUSTION_CHAMBER_PRESSURE_SENSOR_ADC_CHANNEL_INDEX_2 7

// CHECK IF GOOD
#define ENGINE_COMBUSTION_CHAMBER_1_THERMISTANCE_ADC_CHANNEL_INDEX 8
#define ENGINE_COMBUSTION_CHAMBER_2_THERMISTANCE_ADC_CHANNEL_INDEX 9
#define ENGINE_COMBUSTION_CHAMBER_3_THERMISTANCE_ADC_CHANNEL_INDEX 10
#define ENGINE_COMBUSTION_CHAMBER_4_THERMISTANCE_ADC_CHANNEL_INDEX 11
#define ENGINE_COMBUSTION_CHAMBER_5_THERMISTANCE_ADC_CHANNEL_INDEX 12
#define ENGINE_COMBUSTION_CHAMBER_6_THERMISTANCE_ADC_CHANNEL_INDEX 13
#define ENGINE_COMBUSTION_CHAMBER_7_THERMISTANCE_ADC_CHANNEL_INDEX 14
#define ENGINE_COMBUSTION_CHAMBER_8_THERMISTANCE_ADC_CHANNEL_INDEX 15