#pragma once

typedef enum {
  ENGINE_STATE_INIT,
  ENGINE_STATE_IDLE,
  ENGINE_STATE_ARMING,
  ENGINE_STATE_READY,
  ENGINE_STATE_IGNITION,
  ENGINE_STATE_POWERED_FLIGHT,
  ENGINE_STATE_UNPOWERED_FLIGHT,
  ENGINE_STATE_ABORT
}
EngineState;